name: Build and Publish Docker Image

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Extract Tag or Set Latest
        id: vars
        run: |
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            TAG_NAME=${GITHUB_REF#refs/tags/}
          else
            TAG_NAME="latest"
          fi
          echo "TAG_NAME=${TAG_NAME}" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: echo $GITHUB_TOKEN | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and Tag Docker Image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository }}
          IMAGE_NAME=${IMAGE_NAME,,} # to lowercase
          echo "IMAGE_NAME=${IMAGE_NAME}" >> $GITHUB_ENV
          
          docker build --no-cache . -t ${IMAGE_NAME}:${TAG_NAME}
          docker tag ${IMAGE_NAME}:${TAG_NAME} ${IMAGE_NAME}:latest

      - name: Push Docker Image to GHCR
        run: |
          docker push ${IMAGE_NAME}:${TAG_NAME}
          docker push ${IMAGE_NAME}:latest

      - name: Verify Docker Image
        run: docker images | grep "${IMAGE_NAME}"

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /home/xcoptech/service/destiny

            sudo docker compose pull
            sudo docker compose up -d
            sudo docker image prune -af
